In [120]:
import numpy as np
import matplotlib.pyplot as plt

In [121]:
# Activation Functions

class Sigmoid:
    def evaluate(self, x):
        return 1/(1+np.exp(-x))
    
    def gradient(self,x):
        return np.exp(-x)/(1+np.exp(-x))**2
    
class ReLU:
    def evaluate(self, x):
        return np.maximum(0,x)
    
    def gradient(self, x):
        if x >= 0:
            return 1
        else:
            return 0
        
class Softmax:
    def evaluate(self, x):
        return np.exp(x)/sum(np.exp(x))
    
    def gradient(self,x):
        n = len(x)
        S = self.evaluate(x)
        grad = np.zeros((n,n))
        for i in range(n):
            for j in range(i):
                grad[i,j] = -S[j]*S[i]
                grad[j,i] = grad[i,j]
            grad[i,i] = S[i]*(1-S[1])
        return grad
    

In [122]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
# Loss Functions 
        
class CrossEntropy:
    # Note: y needs to be encoded as classes 0,1,2,...
    def evaluate(self, y_hat, y):
        return np.log(y_hat[y])
    
    def gradient(self, y_hat, y):
        grad = np.zeros(len(y_hat))
        grad[y] = 1/np.log(y_hat[y])
        return grad

In [124]:
# Optimisation Methods

class SGD:
    def 

SyntaxError: invalid syntax (<ipython-input-124-710cf74a44b6>, line 4)

In [126]:
class DenseLayer:
    
    #TODO:
    #Make no activation for input
    #
    def __init__(self, activation, n_nodes, is_input = False):
        self.activation = activation
        self.n_nodes = n_nodes
        self.is_input = is_input
        
    def FwdPropOutput(self, prev):
        if not self.is_input:
            self.z = np.matmul(self.weights, prev) + self.bias
            self.a = self.activation.evaluate(self.z)
        else:
            self.a = prev
        return self.a

In [139]:
class Network:
    def __init__(self, layers):
        self.layers = layers
        self.n_layers = len(self.layers)
        for i in range(1,self.n_layers):
            this_length = self.layers[i].n_nodes
            prev_length = self.layers[i-1].n_nodes
            self.layers[i].weights = np.random.normal(0.5,1, this_length*prev_length).reshape(this_length, prev_length)
            self.layers[i].bias = np.random.normal(0.5,1,1)
            
    def FwdProp(self, x):
        for layer in self.layers:
            x = layer.FwdPropOutput(x)
        return x
    
    def BackProp(self, y, loss):
        deltas = [None]*self.n_layers
        delta_ws = [None]*self.n_layers
        delta_bs = [None]*self.n_layers
        
        deltas[-1] = np.matmul(loss.gradient(self.layers[-1].a, y), self.layers[-1].activation.gradient(self.layers[-1].z))
            
        return deltas[-1]
        
        
        

In [140]:
act = Softmax()
l1 = DenseLayer(act, 5, is_input = True)
l2 = DenseLayer(act, 3, is_input = False)

In [141]:
nn = Network([l1,l2])

In [142]:
imput = np.array([1,2,3,4,5])
nn.FwdProp(imput)

array([4.15119034e-01, 5.84337390e-01, 5.43575889e-04])

In [143]:
l = CrossEntropy()

In [144]:
nn.BackProp(0, l)

array([-1.96259588e-01,  2.75901206e-01,  2.56655223e-04])